- Code/autopkglib/InstallFromDMG.py
- Code/autopkglib/Installer.py
Reference to URLDownloader corrected.
> Typo fix in description of processors

- Code/autopkgserver/autopkginstalld
Nerd alert.
I was digging through the code and saw this. Hopefully I'll have some time soon to do a lot more housecleaning stuff.
> Fix missing WS on print statement.

- Code/autopkglib/URLDownloader.py
PR for autopkg/autopkg#126. Feedback welcome!
> Urldownloader content encoding

- Code/autopkglib/PackageRequired.py
Per autopkg/jessepeterson-recipes@6c0a210c47795249080b91fadd8eade34303b043 comment from @gregneagle.
> Added PackageRequired processor

- Code/autopkg
- Code/autopkglib/__init__.py
Credit to @nmcspadden for finding this.
> Fixed typo: identifer → identifier

- Code/autopkglib/CodeSignatureVerifier.py
In two places there was if/then or assignment when all that was needed was a return of bool.
> just return bools of test

- Code/autopkglib/FileFinder.py
Added that the returned value is a full path and not just the filename.
> Updated description of output variable

- Code/autopkglib/DmgMounter.py
- Code/autopkglib/PlistReader.py
https://github.com/autopkg/autopkg/issues/308
> PlistReaderFix

- Code/autopkglib/URLDownloader.py
I found that for **ftp://** URLs (like those used by HP in their product driver downloads), autopkg always reports the file as newly downloaded. This patch allows `URLDownloader` to at least grab the file size from the FTP 213 response code that curl elicits by default via a SIZE command.
I also check for FTP success (125 or 150) and failure (55x) and map it to HTTP 200 and 404 in case any future changes check for those values in `header['http_result_code']`.
> Added FTP response checking to URLDownloader processor

- Code/autopkglib/URLTextSearcher.py
Further to #384, also add support for additional curl options to URLTextSearcher.
> Add optional curl options to URLTextSearcher

- Code/autopkglib/CURLDownloader.py
- Code/autopkglib/URLDownloader.py
I did both CURLDownloader and URLDownloader together because CURLDownloader just calls URLDownloader anyway.
> CURL/URLDownloader with flake8 + isort

- Code/autopkglib/PkgCopier.py
> PkgCopier with flake8+isort

- Code/autopkglib/__init__.py
I tested several autopkg commands and verified the behavior was correct:
```
$ autopkg run -vv Firefox.download
$ autopkg repo-add recipes
$ autopkg repo-delete recipes
$ autopkg list-recipes
$ autopkg repo-list
$ autopkg verify-trust-info
```
> __init__.py with flake8 + isort

- Scripts/generate_processor_docs.py
The purpose of this is to separate out some of the existing functionality into smaller functions, for added testability in the future. The primary and more immediate objective is to allow taking different actions based on the results. The next PR in this stack will be adding an argument to select a specific processor to update.
Testing by running:
```
./generate_processor_docs.py 1.0.5
Cloned to /var/folders/th/3tqg05g54f73x0k_mstm5wy1_0g_xw/T/tmp7bf6sD.
commit df99d8a005bd4350b8662f4e794c1df53d10d0fa
Author: Nick McSpadden <nmcspadden@gmail.com>
Date:   Thu May 16 14:10:54 2019 -0700
Updating Wiki docs for release 1.0.5
diff --git a/Processor-AppPkgCreator.md b/Processor-AppPkgCreator.md
index f2a1a4f..09abb19 100644
--- a/Processor-AppPkgCreator.md
+++ b/Processor-AppPkgCreator.md
@@ …
```
> Moving sidebar into separate function

- Scripts/generate_processor_docs.py
Adding a `-p` argument to generate_processor_docs that lets you update a single processor at a time, instead of everything at once.
When using it to specify a processor with changes:
```
$ ./Scripts/generate_processor_docs.py 1.0.5 -p AppPkgCreator
Cloning AutoPkg wiki..
Cloned to /var/folders/th/3tqg05g54f73x0k_mstm5wy1_0g_xw/T/tmphUdiNY.
commit 7471e4fbf6e083e25af9c76d1c82c1c8d77a98be
Author: Nick McSpadden <nmcspadden@gmail.com>
Date:   Thu May 16 22:22:57 2019 -0700
Updating Wiki docs for release 1.0.5
diff --git a/Processor-AppPkgCreator.md b/Processor-AppPkgCreator.md
index f2a1a4f..09abb19 100644
--- a/Processor-AppPkgCreator.md
+++ b/Processor-AppPkgCreator.md
@@ -12,7 +12,7 @@ Calls autopkgserver to create a package from an application.
- **description:** Path to an application …
```
> Adding a per-processor option to generate_processor_docs

- Code/autopkg
- Code/autopkglib/__init__.py
Moving log and log_err to autopkglib so flake8 doesn't complain anymore.
> Fixing flake8 errors

- Scripts/setup_new_recipe_repo.py
One tweak that should bring the script to Python 3 readiness, and another that allows easier use with GitHub SSH keys for org maintainers.
> Adjustments to recipe repository creation script

- Code/autopkglib/URLTextSearcher.py
- Code/tests/test_urltextsearcher.py
- Small refactoring to better structure the code
- Unit tests for URLTextSearcher covering all? its features
> URLTextSearcher unit tests

- Code/autopkglib/URLTextSearcher.py
- Code/tests/test_urltextsearcher.py
Small code style change after discussion in #596 )
> Turn URLTextSearcher class variables into module constants

- Code/autopkg
Alternative syntax for repo-list and list-processors
> Add verbs list-repos and processor-list

- Code/autopkglib/MunkiImporter.py
- Code/autopkglib/URLGetter.py
- Code/autopkglib/__init__.py
- Code/autopkglib/munkirepolibs/AutoPkgLib.py
- Code/autopkglib/munkirepolibs/MunkiLibAdapter.py
- Code/tests/test_autopkglib.py
Some commits from master.. they are now in dev.
> Merge recent changes from master

- CHANGELOG.md
- Code/autopkglib/version.plist
This just keeps dev up to date with master changes to prevent drift.
> Merge recent master commits into dev

- Code/autopkglib/MunkiImporter.py
- Code/autopkglib/munkirepolibs/AutoPkgLib.py
- Code/autopkglib/munkirepolibs/MunkiLib.py
When running AutoPkg for a recipe like `GoogleChrome.munki` and using the `MunkiRepoAdapter`, `MunkiImporter` falsely believes that a match for pkg/pkginfo exists in the repository if _any_ version of `GoogleChrome` exists in the repo. This causes AutoPkg to _not_ upgrade pkgs as they become available.
This differs from the behavior when AutoPkg is using the more common `AutoPkgLib` repo adapter. This repo adapter will only return a match if there is an exact version match.
I believe the problem exists because the Munki matching logic is more permissive. With tools like `munkiimport`, it's useful to show the admin that a package already exists, albeit a different version, "and do you want to replace it?". In AutoPkg, this makes less sense as tasks are run in an automated fashion and an …
> Bug fix: Modify munkiimporter so that it uses consistent pkginfo matching logic

- Code/autopkglib/PkgCreator.py
- Code/autopkglib/PkgExtractor.py
- Code/autopkglib/SignToolVerifier.py
- Code/autopkglib/StopProcessingIf.py
- Code/autopkglib/Versioner.py
- Code/autopkglib/__init__.py
- Code/autopkglib/github/__init__.py
- Code/autopkglib/munkirepolibs/AutoPkgLib.py
- Code/nuget/ChocolateyInstallGenerator.py
- Code/nuget/NuspecGenerator.py
- Code/nuget/generated/_nuspec.py
- Code/tests/test_versioner.py
This PR is the result of running `black .` and nothing more. No functional/logical changes.
> Reapply Python black formatting to codebase

- Code/autopkg
This PR fixes an error that produced unexpected behavior for GitHub orgs with non-alphanumeric characters (e.g. hyphens) (#712).
Rather than expanding the existing regular expression to include the previously-omitted characters (hyphens, dots), this change drops regex in favor of simple "contains" conditions, which should succeed or fail independently of which characters GitHub deems valid for an org or repo name.
`autopkg repo-add` and `autopkg repo-delete` test output below:
These add/delete runs are expected to succeed.
```
% ./Code/autopkg repo-add eth-its/autopkg-mac-recipes
Attempting git clone...
Adding ~/Library/AutoPkg/RecipeRepos/com.github.eth-its.autopkg-mac-recipes to RECIPE_SEARCH_DIRS...
Updated search path:
'.'
'~/Library/AutoPkg/Recipes'
'/Library/AutoPkg/Recipes' …
```
> Fix regex parsing error affecting repo-add and repo-delete

- Code/autopkg
- Code/tests/test_expand_repo.py
This is a follow-up to #715, and resolves a logical error introduced in that fix causing local file paths to be treated as GitHub URLs. This is likely the root cause of lindegroup/autopkgr#666, and may contribute to lindegroup/autopkgr#665 as well.
`autopkg repo-add` and `autopkg repo-delete` test output below. I've included all the tests from #715 in addition to absolute (`.startswith('/')`) and home-relative (`.startswith('~')`) file paths.
`file://` paths aren't addressed here, and have other complications that shouldn't hold up this bug fix.
Home-relative path:
```
% ./Code/autopkg repo-update ~/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes
Attempting git pull for ~/Library/AutoPkg/RecipeRepos/com.github.autopkg.recipes...
Already up to date.
```
```
% ./Code/autopkg repo-add …
```
> Resolve bug preventing repo-update and repo-delete with local file paths

- Code/autopkglib/MunkiImporter.py
So we moved our munki repo recently and from that point on autopkg imported packages with broken `installer_item_location` values. It turns out this was because our mount path contained the substring `pkgs/`
https://github.com/autopkg/autopkg/blob/af858c033643089b8ecbccf0a8ad691d4c28a289/Code/autopkglib/MunkiImporter.py#L384
```
>>> '/mnt/munkipkgs/pkgs/apps/Keka/Keka-1.2.4.dmg'.partition('pkgs/')
('/mnt/munki', 'pkgs/', 'pkgs/apps/Keka/Keka-1.2.4.dmg')
```
This PR *slightly* improves the handling of that by adding a leading `/` to the split value. Conflicts may still occur though.
> Remove path component confusion in munkiimporter

- Code/autopkgserver/packager.py
> allow `-` in the package version as it is  allowed in MacOS

- Code/autopkg
remove notice about autopkg incompatibility on non-macs
> remove incompatibility notice non-macs

- .github/workflows/linting.sh
- .github/workflows/linting.yaml
This GitHub Actions workflow helps keep AutoPkg's codebase tidy and consistent by applying [linting and auto-formatting](https://github.com/autopkg/autopkg/blob/master/CONTRIBUTING.md) to incoming contributions. In doing so, we are slightly lessening the burden placed on contributors, since any code submitted will be automatically aligned with Black formatting and `isort` import order regardless of the contributors' local setup.
The workflow is triggered by pushes to specific branches or pull request submissions. It runs `pre-commit` on the codebase and commits/pushes any changes made by auto-formatters like Python Black. Any linting errors that aren't automatically fixed will result in a CI job failure (which does not prevent merges, but does help to raise visibility).
Contributors who …
> Create linting/auto-formatting workflow in GH Actions

- Code/autopkglib/SparkleUpdateInfoProvider.py
Channels is a Sparkle v2 feature which allows for differing channels to be offered within AppCasts, such as a beta channel (see: https://sparkle-project.org/documentation/publishing/#publishing-an-update).
This PR adds a new input_variable to the SparkleUpdateInfoProvider processor, `update_channel`.
When a value for `update_channel` is specified, each channel/item block is searched for the sparkle:channel element. If this exists and has the same value as what has been passed to the `update_channel` input_variable, this channel/item block is used to get the needed data via the same method as before this PR.
If the channel/item block does not have a channel defined, or it's does and it's not the same value as what has been passed to the `update_channel` input_variable, the channel/item …
> Update SparkleUpdateInfoProvider.py to support channels

- Code/autopkglib/URLDownloaderPython.py
Enhancements and bug fixes for URLDownloaderPython that we have been using in production for a while now.
> Enhancements to URLDownloaderPython

- CHANGELOG.md
- Code/autopkglib/SparkleUpdateInfoProvider.py
- Code/autopkglib/version.plist
Updates dev with latest commits that were merged directly into master recently.
> Merge master into dev

- Code/autopkglib/recipes/__init__.py
> Ignore unused hashes when generating recipe map

- Code/autopkg
> chore: update autopkg

- Code/autopkglib/MunkiImporter.py
This change enables MunkiImporter to create a working <date> type when the pkginfo key being read in is for force_install_after_date, as that's the only key of this type and reading in the serialized plist with a date key set to a variable wouldn't work. Handles if you leave the Z on the end of the datetime format (or otherwise screw it up)
> Special-case force_install_after_date in pkginfo
