- Code/autopkglib/SparkleUpdateInfoProvider.py
For my use case, I have to find the version number for the flat pkg contained in a versioned .dmg file linked from an appcast feed. Since the Sparkle provider already extracts the most reasonable version number possible, I'd like to have it available in my recipes. I hope this seems reasonable!
> Return the version number from SparkleUpdateInfoProvider

- Code/autopkgserver/autopkgserver
- Code/autopkgserver/launch.py
- Code/autopkgserver/launch2.py
The API used by Code/autopkgserver/launch.py were deprecated in 10.10 and a much simpler one was added (see man 3 launch). I added launch2.py using the new API and a version check in autopkgserver to call the correct one.
I don't have a 10.9 machine set up for regression testing so I've only tested the new codepath for 10.10.
> Added support for launchd 2.0 socket retrieval.

- Code/autopkg
Currently there is a trailing period in the output of the 'make-override' command that makes it a pain to quickly copy and paste the path from the output.
Example: http://i.imgur.com/XwMh3kD.gifv
This PR removes that trailing period to making copying and pasting this path easier; especially when making multiple override files back to back for a new setup.
> Removing trailing period from make-override path output

- Code/autopkglib/SparkleUpdateInfoProvider.py
SparkleUpdateInfoProvider.py will always check the Sparkle feed URL, even if a local PKG is specified with -p.  This tells Sparkle to ignore and not check the Sparkle feed URL if a PKG option is specified (which will also prevent the recipe from failing if internet access is unavailable and a local package is provided).
> Suppresses URL check in SparkleUpdateInfoProvider if PKG provided

- Code/autopkglib/github/__init__.py
I just noticed that when I crated an API token using `autopkg search -t ...` it listed the `AutoPkg CLI` token at https://github.com/settings/tokens but was not showing up at https://github.com/settings/applications. This simply updates the info string.
> Use GitHub's settings/tokens path rather than settings/applications.

- Code/FoundationPlist/__init__.py
- Code/autopkg
- Code/autopkglib/AppDmgVersioner.py
- Code/autopkglib/MunkiInstallsItemsCreator.py
- Code/autopkglib/MunkiSetDefaultCatalog.py
- Code/autopkglib/StopProcessingIf.py
- Code/autopkglib/__init__.py
This is a step on the way to making AutoPkg run cross platform, which may never happen. AutoPkg does work just fine for automating the preparation of Windows software for deployment, it just requires an OS X machine to run on.
These changes should in no way affect AutoPkg working on OS X.
TODO:  code would need to be written to abstract the use of Foundation & CoreFoundation on non-OSX platforms.  (NSArray, NSDictionary, and CFPreferences in Code/autopkglib/__init__.py)
The processors with OS X dependencies like AppDmgVersioner, MunkiInstallsItemsCreator, and MunkiSetDefaultCatalog would not be useful on other platforms anyway, so they would not need to be altered.
StopProcessingIf would need altered if used cross platform.
> add try/except blocks for OS X specific imports for use on Windows/Linux

- Code/autopkglib/MunkiImporter.py
Empty pkginfo extension is supported by munkiimport but autopkg doesn't handle it well. This fix took munkiimport's original codes as reference and has been working for me for a year.
> MunkiImporter empty extension fix

- Code/autopkglib/URLDownloader.py
This will allow tools that email AutoPkg error output (like AutoPkgr) to produce clickable URLs. Current behavior causes a trailing colon to render the URL unusable.
This change will remove the trailing colon from the URL, and surround the error message with parentheses to call it out.
> Removed trailing colon from URL in error messages.

- Code/autopkgserver/packager.py
Initial fix for allowing PkgCreator to handle absolute paths in a chown dict.  Currently if an absolute path is provided, autopkgserver will attempt to change owner, group, and mode on that absolute path.  It should always only ever touch things within the pkgroot.
> PkgCreator path joining

- Code/autopkg
- Code/autopkglib/__init__.py
When running a single recipe, a recipe failure is either handled by the individual failing processor and passed up as a ProcessorError and AutoPkg reports a failure, or AutoPkg stops with an exception. Either way, one recipe failed, and you get immediate information about it.
However, when running multiple recipes, an unhandled exception halts AutoPkg execution, rather than continuing with the next recipe. This *should* only be a problem with custom processors, but in practice, and as non standard-library processors (included in recipe repos?) proliferate, those which don't look for exceptions and in-turn raise ```ProcessorError``` have the potential to halt multiple-recipe runs.
This isn't a huge problem, but it does prevent the final reporting from happening. When running a long list of …
> Make run_recipes() except block handle failures more broadly.

- Code/autopkg
When running with multiple recipes. (Fixes #223)
> Apply make_suggestions and search_github to parent load_recipe function

- Code/autopkglib/SparkleUpdateInfoProvider.py
* `get_feed_data()` did not check that any `channel/item` items were
actually found/returned, which would lead to an `IndexError` in `main()`.
* Discovered when running for  'com.github.jps3.download.fseventer’
which is returning `200 OK` for a `text/html` document (contents of
which simply state that site is temporarily offline). Hence the Processor
would chug along without a care in the world.
> SparkleUpdateInfoProvider: Raise ProcessorError if channel items list empty

- Code/autopkglib/CURLDownloader.py
I decided to go with using a temporary file and move it in place if the processor downloaded something new. This imports the tempfile module.
> Use a temporary file in CURLDownloader

- Code/autopkglib/CodeSignatureVerifier.py
Input path is now always globbed instead of globbing only within a mounted disk image. Logic copied and slightly modified from the Installer processor.
> CodeSignatureVerifier glob fix

- Code/autopkglib/CodeSignatureVerifier.py
Print a warning when expected_authority_names array is used for verifying .app bundles. The expected_authority_names support is a leftover from the early days of CodeSignatureVerifier and should be completely deprecated in some future AutoPkg release. This change should only print a warning, no change in functionality was made.
> Warn on expected_authority_names and .app bundles

- Code/autopkglib/SparkleUpdateInfoProvider.py
* It would appear that the recent change from using urllib to curl
introduced a subtle bug wherein the SparkleUpdateInfoProvider processor
was effectively ignoring `appcast_request_headers`.
* The fix: within the `get_feed_data()` function, the line calling
`self.fetch_content()` was giving `appcast_query_pairs` as the second
argument (which `get_feed_data()` took as its `headers=` argument).
Since `appcast_query_pairs` are url encoded in the code block
immediately before this call, all that’s missing was to remove the
extraneous argument with a corrected `headers=` one.
> Fixed SparkleUpdateInfoProvider ignoring appcast_request_headers

- Code/autopkglib/URLDownloader.py
Add the --fail option to curl to make 400 errors (in particular 404
errors) return a non-zero exit code
Return an error from the processor when curl exits with a non-zero
code (i.e. error)
(as mentioned as an option in pr #273 )
> URLDownloader.py: stop processor on bad status from curl

- Code/autopkg
Noticed when virustotal processor was not running after recipe runs. Not sure if there are other places where this is defined or whether this is enough to fix it but here goes :)
> Fixed preprocessors erroneously assigned as postprocessors

- Code/autopkgserver/packager.py
Added code that prints out the text that is causing "Invalid version" errors.
> Improved "Invalid version" error reporting

- Code/autopkglib/DmgCreator.py
Added default filesystem (Journaled HFS+) and support for overriding it to DmgCreator.
It seems that `hdiutil create` on  High Sierra currently creates disk images with APFS filesystem by default if the `-fs` argument is not used. This is probably not what the default should be for AutoPkg.
> Define filesystem when creating disk images

- Code/autopkglib/MunkiImporter.py
I found that I needed to add this for an item where an installs array of a single `bundle` type was merged into `pkginfo` using `MunkiPkginfoMerger` prior to calling `MunkiImporter`.
It's not quite obvious to me why this wasn't needed originally in #216, but it seems like without it, the item never gets added to the pkgdb. Current the applications "table" only contains keys which are also valid for `bundle` types, so this seems safe enough, but would appreciate a sanity check.
> MunkiImporter: add bundle types when making catalog db

- Code/autopkglib/CodeSignatureVerifier.py
This PR adds a number of new things and modernizations to CodeSignatureVerifier without changing current behavior too much.
- Added `strict_verification` variable to control whether to pass `--strict`, `--no-strict` or nothing at all to codesign. The default is to not pass anything unless specifically defined. This will make the strict verification an opt-in for recipe writers but I think it's better than breaking things. Using this in a recipe might look like this:
```
<dict>
<key>Processor</key>
<string>CodeSignatureVerifier</string>
<key>Arguments</key>
<dict>
<key>input_path</key>
<string>%pathname%/Google Chrome.app</string>
<key>requirement</key>
<string>(identifier "com.google.Chrome" or identifier "com.google.Chrome.beta" or identifier "com.google.Chrome.dev" or identifier …
```
> New options for CodeSignatureVerifier

- Code/autopkglib/FlatPkgUnpacker.py
- Code/autopkglib/PkgPayloadUnpacker.py
- Code/autopkglib/PkgRootCreator.py
This PR is to replace the use of `os.mkdir` with `os.makedirs` for three of the core processors:
- FlatPkgUnpacker
- PkgPayloadUnpacker
- PkgRootCreator
Existing processors that already use `os.makedirs` are:
- MunkiImporter
- AppPkgCreator
- PkgExtractor
- URLDownloader
- Unarchiver
The thinking being that some of these processors will create intermediary directories if so instructed, while others won't. For the sake of consistency, it makes sense to use `os.makedirs` for all of the above.
`os.makedirs` has the same signature as `os.mkdir`, so there shouldn't be any issues.
> Use `os.makedirs` instead of `os.mkdir` for all core processors.

- Code/autopkg
- Code/autopkglib/GitHubReleasesInfoProvider.py
- Code/autopkglib/__init__.py
- Code/autopkglib/github/__init__.py
These changes swap out urllib2 for curl when making GitHub API calls. I tried to keep changes to existing behaviour at minimum but some things are different:
- When using curl, we can't easily get the HTTP status code. I therefore removed the status code from the `call_api()` return value and just return the json response.
- When doing `autopkg search -t`, we're not trying to create a new token over the GH API. Instead just display a link where a token can be manually created and wait for user to copy/paste it back in.
This PR doesn't include any changes to the token behaviour, that will be a separate PR.
> Use curl for GitHub API calls instead of urllib2

- ReadMe.md
Update ReadMe to: reflect current (and previous) names for macOS;
clarify that the ‘git’ terminal trick works in 10.9 and later; update
names of software distribution systems to reflect the current names of the three most popular products in the repo.
> Update ReadMe to modern terms

- Code/autopkg
This adds a "-f"/"--force" option to `autopkg make-override`, which allows the admin to force create a new override even if one already exists. This is useful if a recipe has completely changed behavior/input variables, and the admin wants to start over. 
Testing when an override already exists:
```
$ autopkg make-override XcodeResigned.munki
An override plist already exists at /Users/nmcspadden/Library/AutoPkg/RecipeOverrides/XcodeResigned.munki.recipe, will not overwrite it.
$ autopkg make-override XcodeResigned.munki --force
Override file saved to /Users/nmcspadden/Library/AutoPkg/RecipeOverrides/XcodeResigned.munki.recipe
$ autopkg make-override XcodeResigned.munki -f
Override file saved to /Users/nmcspadden/Library/AutoPkg/RecipeOverrides/XcodeResigned.munki.recipe
```
Testing when …
> Adding -f/--force option for make-override

- Code/autopkg
This adds a "-q" / "--quiet" option to suppress searching Github for recipes if a matching recipe is not found.
Before:
```
$ autopkg info TotallyNotReal.download
Didn't find a recipe for TotallyNotReal.download.
Search GitHub AutoPkg repos for a TotallyNotReal.download recipe? [y/n]: n
```
If you are using AutoPkg in an automated script, and this ever is passed a bad value, the script halts here waiting for user input. To address this, we can forcefully suppress this input request.
Info:
```
$ autopkg info TotallyNotReal.download
Didn't find a recipe for TotallyNotReal.download.
Search GitHub AutoPkg repos for a TotallyNotReal.download recipe? [y/n]: n
No valid recipe found for TotallyNotReal.download
$ autopkg info TotallyNotReal.download -q
No valid recipe found for …
```
> Add -q/--quiet option to suppress Github search and suggestions

- Code/autopkglib/URLDownloader.py
We noticed a lot of unnecessary re-downloads for the current Tower.zip package. It turns out that URLDownloader ignored header results (etag, last-modified) after a HTTP 307 redirect. Curl downloads the files, but autopkg did not store the final etag value.
Example path for tower:
```
curl  --silent --show-error --no-buffer --fail --dump-header - --speed-time 30 --location --url https://www.git-tower.com/download  --output /dev/null
HTTP/1.1 301 Moved Permanently
Date: Tue, 11 Sep 2018 15:05:00 GMT
Server: Apache/2.4.29
Location: https://updates.fournova.com/tower3-mac/stable/releases/latest/download
Cache-Control: max-age=900
Expires: Tue, 11 Sep 2018 15:20:00 GMT
Content-Length: 354
Content-Type: text/html; charset=iso-8859-1
HTTP/1.1 307 Temporary Redirect
Server: Cowboy
Connection: …
```
> Fix URLDownloader tripping over 307 redirect

- Code/autopkg
Normalize the `recipe_path` variable in `recipe_in_override_dir` so that we can check if a recipe override file provided with a relative path is within an override directory.
Right now, if my working directory is `~/AutoPkg`, and my override directory is set to `~/AutoPkg/RecipeOverrides`, and I pass `./RecipeOverrides/MyRecipe.recipe` to this function, it will fail. 
This will fail because the function checks to see if the string `./RecipeOverrides/MyRecipe.recipe` starts with `~/AutoPkg/RecipeOverrides`.
Fixes #436 
Run `verify-trust-info` and get an `OK` response for both relative and absolute paths:
```bash
$ autopkg verify-trust-info -vv ./RecipeOverrides/MSWord2016.munki.recipe
./RecipeOverrides/MSWord2016.munki.recipe: OK
```
```bash
$ autopkg verify-trust-info -vv …
```
> Normalize recipe path in recipe_in_override_dir

- Code/autopkglib/PkgRootCreator.py
As per discussion on MacAdmins Slack on 2019-01-21, added text to the PkgRootCreator description to highlight that it can be used for generic directory creation.
> Update description of PkgRootCreator

- Code/autopkg
Autopkg should return non-zero (specifically, exit 1) if it can't verify trust because the recipe is not found.
Solves #458.
> Failing to verify trust due to NOT FOUND will now exit 1

- Code/autopkglib/MunkiImporter.py
This makes some very basic changes:
1) Sort the imports with isort
2) The exception handling uses the py3 compatible "with Exception as variable" syntax
3) All test conditions of "if not X in Y" have been changed to "if X not in Y" based on flake8 standards
4) Removed trailing whitespace
> Basic flake8, isort and py3 compatibility

- Code/autopkglib/MunkiImporter.py
Adding a metadata_additions key to the input variables for MunkiImporter.
This allows passing a dictionary of keys/values that will be directly added into the _metadata key of the pkginfo that is generated.
I tested this using Firefox.munki. This is what my override's input variables look like, where I added the `metadata_additions` dictionary:
```
cat /Library/AutoPkg/RecipeOverrides/Firefox.munki.recipe
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>Identifier</key>
<string>local.munki.Firefox</string>
<key>Input</key>
<dict>
<key>metadata_additions</key>
<dict>
<key>autopkg_build</key>
<string>%AUTOPKG_VERSION%</string>
</dict>
<key>LOCALE</key> …
```
> MunkiImporter - Adding metadata_additions

- Code/autopkglib/DmgMounter.py
Because of the use of `print` in the self-executing part of the processor, I imported the future Python-3 compatible print syntax.
> DmgMounter with flake8 + isort, using future print()

- Code/autopkglib/GitHubReleasesInfoProvider.py
cmp() doesn't exist in Python3, so I replaced the functionality based on the suggested solutions from What's New In Python 3.0: https://docs.python.org/3.0/whatsnew/3.0.html#ordering-comparisons
The result seems to be the same. Current cmp() implementation:
```
GitHubReleasesInfoProvider
{'Input': {'asset_regex': u'^munkitools-3.*?pkg$',
'github_repo': u'munki/munki',
'include_prereleases': u''}}
GitHubReleasesInfoProvider: Matched regex '^munkitools-3.*?pkg$' among asset(s): munkitools-3.6.2.3776.pkg
GitHubReleasesInfoProvider: Selected asset 'munkitools-3.6.2.3776.pkg' from release 'Munki 3.6.2 Official Release'
{'Output': {'release_notes': u'...',
'url': u'https://github.com/munki/munki/releases/download/v3.6.2/munkitools-3.6.2.3776.pkg',
'version': u'3.6.2'}}
```
With the new …
> GithubReleasesInfoProvider with flake8 + isort, replace cmp

- Code/autopkglib/PathDeleter.py
Also replaced 'basestring' with 'str', as basestring no longer exists in py3. I verified that this still works in python2.
> PathDeleter with flake8+isort

- Code/autopkglib/MunkiInstallsItemsCreator.py
Also replaced 'basestring' with 'str', as basestring no longer exists in py3. I verified that this still works in python2.
> MunkiInstallsItemCreator with flake8 + isort

- Scripts/generate_processor_docs.py
This fixes generate_processor_docs.py to ensure the sidebar always ends up being sorted alphabetically.
Running this:
```
$ generate_processor_docs.py 1.0.5
```
produces (processor-based results are truncated):
```
diff --git a/_Sidebar.md b/_Sidebar.md
index 1715e7b..75b75c6 100644
--- a/_Sidebar.md
+++ b/_Sidebar.md
@@ -29,10 +29,10 @@
* [[AppDmgVersioner|Processor-AppDmgVersioner]]
* [[AppPkgCreator|Processor-AppPkgCreator]]
* [[BrewCaskInfoProvider|Processor-BrewCaskInfoProvider]]
-      * [[CodeSignatureVerifier|Processor-CodeSignatureVerifier]]
-      * [[Copier|Processor-Copier]]
* [[CURLDownloader|Processor-CURLDownloader]]
* [[CURLTextSearcher|Processor-CURLTextSearcher]]
+      * [[CodeSignatureVerifier|Processor-CodeSignatureVerifier]]
+      * [[Copier|Processor-Copier]]
* …
```
> generate_processor_docs sorts the sidebar alphabetically

- Code/autopkglib/__init__.py
This opens the door for AutoPkg on alternative platforms. The memoization is so that we don't have to make another call to platforms() every time we want to do this lookup - the result is cached in each invocation.
> Adding platform-specific determination functions

- .pre-commit-config.yaml
Flake8 was being too aggressive, so let's limit to python-2 limitations only.
Also removed an extra spacing in the pre-commit file itself.
Before, with py3 flake8 being run (examples, results are edited for brevity):
```
$ pre-commit run --all-files
black....................................................................Passed
isort....................................................................Passed
Flake8...................................................................Failed
hookid: flake8
Code/autopkglib/github/__init__.py:66:21: F821 undefined name 'raw_input'
Code/FoundationPlist/FoundationPlist.py:144:12: F821 undefined name 'buffer'
Code/autopkgserver/launch.py:16:1: F403 'from ctypes import *' used; unable to detect undefined names
Code/autopkgserver/launch.py:18:8: F405 …
```
> Limit flake8 to python2 only

- Code/autopkglib/URLDownloader.py
xattr module doesn't exist on Windows, so this gates it to a Mac-only import. There's no current expectation that any of this will run on other platforms yet. This is just to allow importing of AutoPkg processors to work on alternate platforms without error (so unit tests can be run on non-macOS, to start with).
> Allowing URLDownloader to be imported on non-Mac platforms

- Code/autopkg
- Code/autopkglib/AppDmgVersioner.py
- Code/autopkglib/DmgMounter.py
- Code/autopkglib/MunkiInstallsItemsCreator.py
- Code/autopkglib/MunkiSetDefaultCatalog.py
- Code/autopkglib/StopProcessingIf.py
- Code/autopkglib/__init__.py
- Code/autopkglib/github/__init__.py
This PR is the implementation of [suggestion](https://groups.google.com/d/msg/autopkg-discuss/YcO2oQR5JME/-19T870MAgAJ) in Google group [thread](https://groups.google.com/forum/#!topic/autopkg-discuss/YcO2oQR5JME) about Python2 EOL..
It does two things:
- ~~Moves `log()` and `log_err()` functions from `autopkg` to `autopkglib`. ba270f1~~ Already in master
- Replaces `print()` function with `log()` and `log_err()` where it makes sense. 1af50fd6d24ba8179227c053164ebef3c07c8ac8
- Remove now unnecessary `print_function` imports da82c92626d881415d81a15b76854633852a41fd
- Switch `ID NOT FOUND` message from stdout to stderr 5e06c381ed8b0bbfa3a6026566fd89715d824e93
> Log instead of print

- .gitignore
- Code/autopkglib/__init__.py
- Code/tests/test_autopkglib.py
- Code/tests/test_filefinder.py
- python2_requirements.txt
This gets the template in place for doing unit testing for AutoPkg. To start with, I provided a unit test for one Processor (FileFinder, because it's easy)
To run the tests, you can do it using the unittest module via the command line. You can do it in a virtualenv, or if you feel like messing with system python, you can install mock there:
```
$ PATH=/usr/bin python -m unittest discover
..............
----------------------------------------------------------------------
Ran 14 tests in 0.026s
OK
```
If you want verbose results for the tests:
```
$ PATH=/usr/bin python -m unittest discover -v
test_get_identifier_from_recipe_file_returns_identifier (tests.test_autopkglib.TestAutoPkg)
get_identifier_from_recipe-file should return identifier. ... ok …
```
> Adding some basic unit tests to AutoPkg

- Code/autopkglib/SparkleUpdateInfoProvider.py
FWIW, I accidentally type "SparkleUpdateProvider" constantly.
> Fix class name in docstring

- Code/autopkg
Nearly all of the AutoPkg verbs share a common trait of generating an optparse parser and parsing the arguments. Since they all behave identically, I've factored out this commonality into two functions:
`gen_common_parser()`, which produces an optparse object. This can eventually be used to pre-configure our option parsing with more flexibility without having to change all future callsites.
`common_parse()`, which parses the options and returns a tuple of options and arguments. This can also store the results somewhere else in the future, without having to change all future callsites.
Adding new verbs becomes slightly simpler, because argument handling is now factored out with these helper functions.
> Adding a common argument parser

- Code/autopkglib/PkgCopier.py
- Code/tests/test_pkgcopier.py
**Summary**
PkgCopier doesn't correctly handle a case where the input `source_pkg` is a glob but no `pkg_path` is specified - it creates a file that is the name of the actual glob, not the glob match - like "*.pkg".
This fixes  #560 .
**Testing**
I edited GoogleEarth.pkg.recipe so that the PkgCopier processor had no `pkg_path` variable:
```
<dict>
<key>Processor</key>
<string>PkgCopier</string>
<key>Arguments</key>
<dict>
<key>source_pkg</key>
<string>%pathname%/Install Google Earth*.pkg</string>
</dict>
</dict>
```
On master, it does something unexpected:
```
PkgCopier
{'Input': {'source_pkg': u'/Users/nmcspadden/Library/AutoPkg/Cache/com.github.autopkg.pkg.google-earth/downloads/GoogleEarth.dmg/Install Google Earth*.pkg'}}
PkgCopier: Mounted disk image …
```
> PkgCopier now uses the correct matched glob name by default

- Code/autopkglib/URLGetter.py
- Code/autopkglib/__init__.py
This PR was split from #446 to simplify the review.
Goal of `URLGetter` processor is to implement common funcionality used by following items in one place:
- `GitHubReleasesInfoProvider` processor (See changes in #549)
- `GitHubSession` class (See change in #548)
- `SparkleUpdateInfoProvider` processor (See change in #547)
- `URLDownloader` processor (See change in #545)
- `URLTextSearcher` processor  (See change in #546 )
Basically we want to deduplicate similiar code handling following:
- Selecting desired `curl` binary to be used.
- Adding items to `curl_cmd` array like `--header` and other custom `curl` options.
- Using subprocess to launch `curl`
- Parse `curl` output including HTTP headers, FTP headers and possible errors
`URLGetter` processor is **not intended to be used directly** …
> URLGetter processor

- Code/autopkglib/URLDownloader.py
- Code/autopkglib/URLGetter.py
- Code/autopkglib/__init__.py
This PR was split from #446. It should be merged **after** PR #544 (`URLGetter`). Branch `urlgetter-urldownloader` includes code from branch `urlgetter` in order for `URLDownloader` to work. `URLGetter` should be reviewed in #544.
`URLDownloader` was refactored in following way:
- `URLDownloader` is now subclass of `URLGetter`
- Functionality like executing `curl` and parsing headers was moved to `URLGetter`
- xattr code outside of class was moved into the class
- Method `main()` was split into many methods
- Some local variables are now instance variables
> URLDownloader refactoring using URLGetter

- Code/autopkglib/URLGetter.py
- Code/autopkglib/URLTextSearcher.py
- Code/autopkglib/__init__.py
This PR was split from #446. It should be merged **after** PR #544 (`URLGetter`). Branch `urlgetter-urltechsearcher` includes code from branch `urlgetter` in order for `URLTextSearcher` to work. `URLGetter` should be reviewed in #544.
`URLTextSearcher` was refactored in following way:
- `URLTextSearcher` is now subclass of `URLGetter`
- Functionality like executing `curl` was moved to `URLGetter`
- Renamed `get_url_and_search()` method to `re_search()` since URL stuff is done in superclass.
- Some local variables are now instance variables
> URLTextSearcher refactoring using URLGetter

- Code/autopkglib/SparkleUpdateInfoProvider.py
- Code/autopkglib/URLGetter.py
- Code/autopkglib/__init__.py
This PR was split from #446. It should be merged **after** PR #544 (`URLGetter`). Branch `urlgetter-sparkleupdateinfoprovider` includes code from branch `urlgetter` in order for `SparkleUpdateInfoProvider` to work. `URLGetter` should be reviewed in #544.
`URLTextSearcher` was refactored in following way:
- `SparkleUpdateInfoProvider` is now subclass of `URLGetter`
- Functionality like executing `curl` was moved to `URLGetter`
- Some of the code from `get_feed_data()` was split into methods `build_url()`, `determine_version()`, `parse_feed_data`.
- Some of the code from `main()` was split into methods `handle_pkginfo()`
- Some local variables are now instance variables
- `SparkleUpdateInfoProvider` now supports `curl_opts` variable
> SparkleUpdateInfoProvider refactoring using URLGetter

- Code/autopkglib/URLGetter.py
- Code/autopkglib/__init__.py
- Code/autopkglib/github/__init__.py
This PR was split from #446. It should be merged **after** PR #544 (`URLGetter`). Branch `urlgetter-githubsession` includes code from branch `urlgetter` in order for `GitHubSession` to work. `URLGetter` should be reviewed in #544.
`GitHubSession` was refactored in following way:
- `GitHubSession` is now subclass of `URLGetter`
- Functionality like executing `curl` and parsing headers was moved to `URLGetter`
- `GitHubSession` now can be initialized with `CURL_PATH` and `curl_opts` environment variables.
- Some local variables are now instance variables
> GitHubSession refactoring using URLGetter 

- Code/autopkglib/GitHubReleasesInfoProvider.py
- Code/autopkglib/URLGetter.py
- Code/autopkglib/__init__.py
- Code/autopkglib/github/__init__.py
This PR was split from #446. It should be merged **after** PR #544 (`URLGetter`) and #548 (`GitHubSession`). Branch `urlgetter-githubreleasesinfoprovider` includes code from branch `urlgetter` and `urlgetter-githubsession` in order for `GitHubReleasesInfoProvider` to work. `URLGetter` should be reviewed in #544. Changes to GitHubSession should be reviewed in #548.
`GitHubReleasesInfoProvider` was refactored in following way:
- Added support for `curl_opts` and `CURL_PATH` environment variables. If set they are passed to `GitHubSession`.
> GitHubReleasesInfoProvider refactoring using URLGetter

- Code/autopkglib/__init__.py
Since we now have all the URLGetter related branches merged into `new_urlgetter` we can safelly remove the `curl_cmd()` function from autopkglib since it is not needed anywhere.
> URLGetter Remove curl_cmd() from autopkglib

- Code/autopkg
- Code/autopkglib/PkgCopier.py
- Code/autopkglib/__init__.py
- Code/tests/e2e_tests.sh
- Code/tests/preferences.json
- Code/tests/preferences.plist
- Code/tests/test_autopkglib.py
- Code/tests/test_pkgcopier.py
**Summary**
This PR will allow preferences to be stored in an external file (currently it must be either in JSON or Plist format). The common parser will add a `--prefs` argument to each argument parser, which allows passing in a file containing key/value pairs to be read in as preferences. 
If a file is passed in, it will take precedence over any macOS preferences that are present. Additionally, changing any of the preference values (by adding or removing a repo, for example) will write back out to the file, and not macOS preferences.
The preferences are now stored in a global object and referenced throughout the code, rather than collected from macOS each time they are queried.
**OS Versions**
This has been tested to work on Windows and macOS.
**Testing**
I've written a number of unit …
> Prefs object

- Code/autopkglib/URLDownloader.py
- Code/autopkglib/URLGetter.py
- Code/autopkglib/github/__init__.py
This PR adds new `prefetch_filename` option to `URLDownloader`. When set to `True`, `curl` is called with `--head` option to retrieve only HTTP headers before actual file download. We try to determine filename from HTTP heades in following order:
1. `Content-Disposition` header
2. `Location` header
3. `filename` option (if set)
4. Last part of url right from the slash (default behaviour)
Solves #432 
Also there is tiny bit of refactoring in 3364221
> Prefetch filename before download

- Code/autopkg
- Code/autopkglib/__init__.py
#565 introduced an unexpected problem where CFPreferencesCopyAppValue via objc is converting integers to Longs, which Python represents by appending an "L" onto the string representation of an int.
You can replicate this by writing an integer via defaults:
```
defaults write com.github.autopkg FOO -integer 100
```
Then using Python to retrieve it:
```
>>> from CoreFoundation import CFPreferencesCopyAppValue
>>> BUNDLE_ID = "com.github.autopkg"
>>> testint = CFPreferencesCopyAppValue("FOO", BUNDLE_ID)
>>> type(testint)
<class 'objc._pythonify.OC_PythonLong'>
>>> testint
100L
```
In order to solve this, we have to actively convert each of the preferences we slurp in from CFPreferences from the custom objc bridged type to a Python primitive type.
> Use only FoundationPlist for macOS, convert Foundation types to Python primitives

- Code/autopkg
- Code/autopkglib/CodeSignatureVerifier.py
- Code/autopkglib/DmgCreator.py
- Code/autopkglib/DmgMounter.py
- Code/autopkglib/FlatPkgUnpacker.py
- Code/autopkglib/MunkiCatalogBuilder.py
- Code/autopkglib/MunkiImporter.py
- Code/autopkglib/MunkiInfoCreator.py
- Code/autopkglib/MunkiInstallsItemsCreator.py
- Code/autopkglib/PkgCreator.py
- Code/autopkglib/PkgExtractor.py
- Code/autopkglib/PkgPayloadUnpacker.py
- Code/autopkglib/SparkleUpdateInfoProvider.py
- Code/autopkglib/URLDownloader.py
- Code/autopkglib/URLGetter.py
- Code/autopkglib/Unarchiver.py
- Code/autopkgserver/autopkginstalld
- Code/autopkgserver/autopkgserver
- Code/autopkgserver/installer.py
- Code/autopkgserver/itemcopier.py
- Code/autopkgserver/launch2.py
- Code/autopkgserver/packager.py
Fixes to get `URLGetter` code working after py2-to-3 conversion. Currently WIP.
- Popen in `URLGetter` is set to text mode by default 5e3c35c. This is handy when expecting **text* output from subprocess we want to parse/searchh. I made text mode configurable 7c05276 because sometimes we might need bytes output. Popen in `CodeSignatureVerifier` set to text mode only 845337e
- URLDownloader str/bytes fixes beac4a5, 1a1777f
- Fixed SparkleUpdateInfoProvider urllib code 3614ee4
- Fixed SparkleUpdateInfoProvider missing curly brackets bug introduced in py2-to-3 branch
- SparkleUpdateInfoProvider  Sort function converted to Python3 e314375 **Plese take a look** at lambda function solution. It works for me but I don't use lambda very often.
- DmgMounter str/bytes fixes f55d3a0
- URLDownloader …
> WIP: Py2 to 3 fixes

- Code/autopkglib/SparkleUpdateInfoProvider.py
- Code/autopkglib/URLDownloader.py
- Code/autopkglib/URLGetter.py
- Code/autopkglib/URLTextSearcher.py
- Code/autopkglib/github/__init__.py
Changes to the `URLGetter` and its subclasses to enable `autopkg/recipes` py23 compatibiilty upgrade with use of `URLGetter`.
Similiar changes future ported to py2-to-3 branch in PR #584
Changes:
- Oriignal `download()` method was renamed to `download_with_curl()` so we can use **download** for simpler uses. b1e449b
- `URLGetter` now has `prepare_curl_cmd()` with *default* `curl` command e45ce95. This is used by new `download()` method and subclasses. 71296de
- We now use inherited methods instead of calling `super()` everywhere. 3a17705
- New simple `download()` method 32267dc for use cases where we don't want to specify `curl` command. It takes http headers too 7b47aa1. We don't use `text` argument in python2 code but it's there for recipe compatibility with python3 version.
> URLGetter py2 upgrades

- Code/autopkglib/SparkleUpdateInfoProvider.py
- Code/autopkglib/URLDownloader.py
- Code/autopkglib/URLGetter.py
When I rebased this branch containg same changes (#584) as in #583 (in master) onto current `py2-to-3` which was merged with master I found out there are few lines wrong.
This was missed in the testing because new `prefetch_filename` feature is not used anywhere  yet and `text_mode` which should be `text` has default value we use most of the times.
Additionally there are few syntax updates for py3 only code.
> Fix merge bugs in py2-to-3

- Code/autopkglib/URLDownloader.py
Adds `verbose_level=2` output to `prefetch_filename()` method printing out what filename was found in which header. This should help autopkg users to debug their recipes.
Requested here https://github.com/autopkg/autopkg/issues/432#issuecomment-559154131
> Add debug output to URLDownloader.prefetch_filename()

- Code/autopkglib/URLGetter.py
There may not be a `url` environment variable in all cases, and this change allows parsing headers regardless.
> Handle missing url environment variable

- Code/autopkglib/EndOfCheckPhase.py
- Code/autopkglib/SparkleUpdateInfoProvider.py
This change updates the docstring for EndOfCheckPhase to provide more information about its conventional use for people reading the [wiki page](https://github.com/autopkg/autopkg/wiki/Processor-EndOfCheckPhase). It also adds a missing space to the SparkleUpdateInfoProvider docstring.
No functional changes to code, so I'm not including any log output here.
> Minor adjustments to processor docstrings

- Code/autopkg
This function appears to have been orphaned at some point in the past (probably here: https://github.com/autopkg/autopkg/commit/b754923952d5c3e6eead1e09d5fa4bc7ff193863). A search through the source code reveals that the only reference to the function is in its own return value. If it was ever used again, it would result in a loop. It can be safely removed.
```
% grep -R 'valid_plist_with_keys(' *
Code/autopkg:def valid_plist_with_keys(filename, keys_to_verify):
Code/autopkg:    return valid_plist_with_keys(recipe_plist, keys_to_verify)
```
> Remove orphaned valid_plist_with_keys() function

- Code/autopkg
Current behavior in AutoPkg 2.0rc1 when a user attempts to run AutoPkg with a version of Python that doesn't support f-strings is the following.
```
% ./autopkg version
2.0.1
% /usr/bin/python ./autopkg version
File "./autopkg", line 126
log_err(f"WARNING: plist error for {filename}: {err}")
^
SyntaxError: invalid syntax
```
This applies to AutoPkg runner scripts that explicitly call `/usr/bin/python /usr/local/bin/autopkg run`, but more broadly applies to users of AutoPkgr 1.5.1 and earlier (https://github.com/lindegroup/autopkgr/issues/635):
The problem here is that "plist error" implies an actual problem worth troubleshooting, when in reality line 126 just happens to be the first line where an f-string is encountered.
It would be nice to be able to use try/except to catch the …
> Generate useful output if AutoPkg detects a Python 2 wrapper

- Code/autopkglib/__init__.py
> Only output traceback if verbosity level > 2

- Code/autopkglib/URLDownloader.py
Some servers disallow HTTP HEAD requests, used to get information about a file. This is the default request type that curl sends when '--head' is passed.
By passing '--request GET' to curl, this default behavior is overridden. curl will now perform a GET request but stop after it receives the headers. This ensures that we get the correct headers for every file (some servers may return different headers for GET vs HEAD) and don't receive HTTP Forbidden errors for an incorrect request type.
Fixes https://github.com/autopkg/autopkg/issues/624
Does anyone have some recipes that should be tested with this change? It only affects prefetch_filename.
> Use a GET request in URLDownloader.prefetch_filename()

- Code/autopkglib/__init__.py
Sample usage:
```
defaults write /tmp/processor.plist ARTICLE_NUMBER '1888'
defaults write /tmp/processor.plist verbose -int 3
plutil -convert xml1 /tmp/processor.plist
export PYTHONPATH=${HOME}/src/autopkg/autopkg/Code 
/Library/AutoPkg/Python3/Python.framework/Versions/Current/bin/python3 ${HOME}/src/autopkg/n8felton-recipes/SharedProcessors/AppleSupportDownloadInfoProvider.py < /tmp/processor.plist
```
Sample Usage 2:
```
export PYTHONPATH=${HOME}/src/autopkg/autopkg/Code 
/Library/AutoPkg/Python3/Python.framework/Versions/Current/bin/python3 ${HOME}/src/autopkg/n8felton-recipes/SharedProcessors/AppleSupportDownloadInfoProvider.py ARTICLE_NUMBER=1888 verbose=3
```
Sample Output in both cases:
```
AppleSupportDownloadInfoProvider: Article URL: https://support.apple.com/kb/DL1888 …
```
> Restores ability to run processors standalone on the commandline

- CONTRIBUTING.md
- ReadMe.md
typo in readme made me notice it hadn't been updated for the now-stable python3/2.x versions, updated verbiage accordingly. Tweaked CONTRIBUTING while I was there
> update README/typo, verbiage tweak in CONTRIBUTING

- requirements.txt
I ran [safety](https://github.com/pyupio/safety) against the requirements.txt file in the repo.
Results:
```
$:  safety check -r requirements.txt
+==============================================================================+
|                                                                              |
|                               /$$$$$$            /$$                         |
|                              /$$__  $$          | $$                         |
|           /$$$$$$$  /$$$$$$ | $$  \__//$$$$$$  /$$$$$$   /$$   /$$           |
|          /$$_____/ |____  $$| $$$$   /$$__  $$|_  $$_/  | $$  | $$           |
|         |  $$$$$$   /$$$$$$$| $$_/  | $$$$$$$$  | $$    | $$  | $$           |
|          \____  $$ /$$__  $$| $$    | $$_____/  | $$ /$$| $$  | $$           |
| …
```
> Bump PyYAML to version to 5.3.1

- Code/autopkglib/URLDownloader.py
This update improves the way the `URLDownloader` parses the `Content-Disposition` HTTP header, the `filename` parameter value in particular.
The value of the `filename` parameter can be quoted, like in the following example:
`Content-Disposition: attachment; filename="sth.dmg"`
Currently, if a server quotes the `filename` parameter value like in the example above, further processing breaks.
This improvement removes the quotation marks, if they are present.  It does not resolve all potential issues with how HTTP headers parsing currently works, it only brings the present parsing mechanism a bit closer to standards.
> improve Content-Disposition filename parsing

- .isort.cfg
- Code/autopkg
- Code/autopkgcmd/__init__.py
- Code/autopkgcmd/opts.py
- Code/autopkgcmd/searchcmd.py
- Code/autopkglib/Copier.py
- Code/autopkglib/InstallFromDMG.py
- Code/autopkglib/Installer.py
- Code/autopkglib/github/__init__.py
- Code/autopkgserver/launch.py
- Code/tests/test_filecreator.py
- Code/tests/test_searchcmd.py
Detailed descriptions of the actual changes are included in the individual commits.
Briefly:
* Apply `black` and `flake8` to the project and bring it into compliance with the `pre-commit` hook to minimize future commit/PR noise.
* Consolidate some duplicated behavior wrt to github access into the github module.
* Factor the search command out into a separate module to improve code quality.
Behavior has not changed for searching:
```
bash-3.2$ autopkg search Firefox >a.txt    ## Pre-change version
bash-3.2$ ./autopkg search Firefox >b.txt  ## Post-change version
bash-3.2$ wc -l a.txt                      ## Confirm some output is produced
81 a.txt
bash-3.2$ wc -l b.txt
81 b.txt
bash-3.2$ diff -u a.txt b.txt              ## Compare output
bash-3.2$ ## No output, no change.
```
Full result …
> Refactor github usage and search command

- Code/autopkglib/SignToolVerifier.py
- Code/autopkglib/URLDownloader.py
- Code/autopkglib/__init__.py
- Code/autopkglib/xattr.py
- Code/tests/test_signtool.py
Add a new processor for Windows `signtool.exe`. Additionally, this includes a wrapper library around `xattr` to so that `URLDownloader` has no more platform specific code in it. This PR depends on #648.
The signtool integration/functional tests pass on Windows and are correctly excluded on other platforms. With the inclusion of the `xattr` changes, autopkg is also now able to download a package on Windows.
Test results:
* [Autopkg Windows example output](https://gist.github.com/linuxfood/eb4efe457bb2415b4c5a9acab52d3b61) - showing successfully downloading a package on Windows. The CodeSignatureVerifier error is expected and a future PR will make sure that CodeSignatureVerifier explicitly to run on Windows.
* [Autopkg macOS run -vv …
> Windows: Add signtool processor 

- Code/autopkglib/__init__.py
- Code/tests/test_autopkglib.py
This PR: removes the `memoize` decorator, fixes a bug in `execute_shell`, and #650 which makes autopkg throw the wrong error in an error case. 
The usages of the `memoize` decorator seem to have all been commented out at one point. The python standard library has an equivalent `lru_cache` decorator that can be used should the need arise for memoize again. The `execute_shell` and wrong error error bugs are just a cases of mistaken identity (wrong methods).
> Cleanup some dead code and fix two bugs

- Code/autopkglib/SignToolVerifier.py
The `signtool_path` input variable had a default value as well as
setting `required: True`. Consequently, it didn't work when running as
part of a larger recipe due to inconsistencies in how autopkg interprets
variables.
> Windows: Fix inputs bug in SigntoolProcessor

- Code/autopkglib/Versioner.py
- Code/autopkglib/__init__.py
- Code/tests/test_versioner.py
- Code for loading plists was moved into base `Processor. self.load_plist_from_file()` method (da3a354 and 428831a) This method could be used in other processors. Ouput:
- If path to plist does not exist or is inaccessible: `File '{plist_path}' does not exist or could not be read.`
- if plistlib fails to load plist: `"{exception_text}: {err}"` where default exception_text is `Unable to load plist`
- There is new Versioner module constant `NO_VERSION_MESSAGE` which is used in both Versioner class and unittests. (8687925)
- Unittest class `TestVersioner` (69d36ca)
Unittest output:
```
test_find_cfbundle_short_version (tests.test_versioner.TestVersioner)
The processor should find version in default CFBundleShortVersionString. ... ok
--
test_find_custom_version …
```
> Versioner changes and unittests

- Code/autopkglib/URLGetter.py
- Code/autopkglib/__init__.py
Currently, if a processor, such as `URLGetter` is imported into an external codebase (for example: `from autopkglib import URLGetter`), `self.env` is set to `None`. This causes problems as `self.env` is expected to be, at a minimum, an empty dictionary.
This commit simply sets `self.env` to `{}` if not provided otherwise.
Here is an example of the error seen before the change:
```
Traceback (most recent call last):
File "/Library/AutoPkg/autopkglib/__init__.py", line 661, in process
self.env = processor.process()
File "/Library/AutoPkg/autopkglib/__init__.py", line 468, in process
self.main()
File "/Library/AutoPkg/autopkglib/MunkiImporter.py", line 250, in main
matchingitem = library.find_matching_pkginfo(pkginfo)
File "/Library/AutoPkg/autopkglib/munkirepolibs/MunkiLibAdapter.py", line …
```
> Support exporting processors outside of AutoPkg

- Code/autopkglib/github/__init__.py
Currently the query sent to Github API fail if the parent recipe name has spaces in it.
``` joaquin  ~/gitlab/autopkg-build   master  autopkg info -p --override-dir="./overrides/" Word2019.munki.recipe
Didn't find a recipe for com.github.dataJAR-recipes.munki.Microsoft Word 2019.
Traceback (most recent call last):
File "/Library/AutoPkg/autopkglib/URLGetter.py", line 196, in execute_curl
errors=errors,
File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/subprocess.py", line 512, in run
output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/opt/local/bin/curl', '--location', '--silent', '--show-error', '--fail', '--dump-header', '-', '-X', 'GET', '--header', 'User-Agent: AutoPkg', '--header', 'Accept: …
```
> Escaped spaces with %20 in recipes with spaces in its name.

- Code/tests/test_chocolatey_packager.py
Python `subprocess` raises `FileNotFound` which wasn't being caught, thus tests were failing on macOS when a chocolatey test case tried to skip based on running `choco.exe --version`.
> Bugfix: Skip chocolatey tests on macOS

- Code/autopkglib/GitHubReleasesInfoProvider.py
- Code/autopkglib/github/__init__.py
###Summary
Add support for AutoPkg users to override the default GitHub API URL and API token location when using the GitHubReleasesInfoProvider. This would allow organizations to search against an internal GitHub Enterprise instance. Additionally, if they choose to search against an internal instance, one can specify a specific token location path on disk (can be either a relative path or absolute path). Or, if they rather just use another Github token, stored elsewhere on disk, they can specify that path (instead of using the default location at ~/.gh_autopkg_token).
###Changes
**GitHubSession:**
I added two new parameters to the GitHubSession constructor - `github_url` and `token_path` - and a new class attribute  `self.url`.
If the `github_url` parameter is set, then it assigns …
> Support Internal GitHub URLs

- .pre-commit-config.yaml
- Code/autopkglib/github/__init__.py
- Code/autopkgserver/packager.py
Per https://github.com/asottile-archive/seed-isort-config, this hook is deprecated now that `isort>=5` has the functionality built-in. This should resolve some of the spurious additions and removals of `known_third_party` entries.
> Update pre-commit-config to remove `seed-isort-config`

- Code/autopkglib/__init__.py
- Code/tests/test_autopkglib.py
- Code/tests/test_preferences.py
When adding global preference support for Windows, saving file-backed (e.g., a json or plist file specified with `--prefs`) became broken on macOS and Linux. This fixes that.
The PR also includes a change that moves the definitions for `log` and `log_err` nearer the top of the module so that they can be used more uniformly, rather than some code paths using `print`.
> Fix file-backed preference saving

- Code/autopkglib/__init__.py
Change the way autopkg discovers built-in processors, and its version file to
use the standard library `pkg_resources` module instead of raw filesystem access.
This is a step towards eventually allowing autopkg to be bundled into a single-file
executable, such as with the standard library `zipapp` module, or [par/xar](https://github.com/facebookincubator/xar/).
I've tested running autopkg in both as a single file executable with par and in the
usual way with the Python code laid out as plain files.
> Resource and processor loading uses `pkg_resources`

- Code/autopkglib/__init__.py
Python 3.8 `platform` module returns `macOS` and not `darwin`, which
breaks AutoPkg loading and saving preferences when using the native
Preference store. Instead use the `sys` module which has more stable identifiers.
To test, I ran AutoPkg under Python 3.7 and 3.8 on macOS and observed that it used
the native preference store when a `--prefs` option is not provided on
the command line.
> Fix platform detection for python >3.7

- Code/autopkg
The `site` module fiddles with the global namespace to add `exit`.
However, this is only meant for interactive use. Generally speaking,
this module is auto-imported so it was never an issue. However, in some
environments the module is not present, or the `-S` flag is used to
disable importing it.
> Remove use of site exit in autopkg main

- Code/autopkg
This PR modifies the `make-override` verb such that if the recipe being overridden or any of its parents contains the [DeprecationWarning processor](https://github.com/autopkg/autopkg/wiki/Processor-DeprecationWarning), the override will not be created by default. An `--ignore-deprecation` flag has also been added, in cases where AutoPkg users want to create the override regardless of deprecation status.
I chose not to add a single-letter equivalent for `--ignore-deprecation` because (a) `-d` is already used and `-i` seemed too general, and (b) ignoring deprecation should be gently discouraged.
```
% ./autopkg make-override -h                                                           
Usage: autopkg make-override [options] [recipe]
Create a skeleton override file for a recipe. It will be …
```
> Add deprecation awareness to make-override

- Code/autopkg
This change allows the `list-processors` verb to respect the `--help` argument like other verbs do.
Before:
```
% ./Code/autopkg list-processors --help
AppDmgVersioner
AppPkgCreator
BrewCaskInfoProvider
CURLDownloader
CURLTextSearcher
ChocolateyPackager
CodeSignatureVerifier
Copier
DeprecationWarning
DmgCreator
DmgMounter
EndOfCheckPhase
FileCreator
FileFinder
FileMover
FlatPkgPacker
FlatPkgUnpacker
GitHubReleasesInfoProvider
InstallFromDMG
Installer
MunkiCatalogBuilder
MunkiImporter
MunkiInfoCreator
MunkiInstallsItemsCreator
MunkiPkginfoMerger
MunkiSetDefaultCatalog
PackageRequired
PathDeleter
PkgCopier
PkgCreator
PkgExtractor
PkgInfoCreator
PkgPayloadUnpacker
PkgRootCreator
PlistEditor
PlistReader
SignToolVerifier
SparkleUpdateInfoProvider
StopProcessingIf
Symlinker
URLDownloader …
```
> Enable --help argument for list-processors verb

- .pre-commit-config.yaml
- CHANGELOG.md
- Code/autopkg
- Code/autopkglib/DeprecationWarning.py
- Code/autopkglib/__init__.py
- Code/autopkglib/github/__init__.py
- ReadMe.md
**This PR adds native support for recipes in yaml format.**
(Includes the changes originally proposed in #617, and adds `make-override`, `new-recipe`, and `search` yaml support.)
The primary benefit of yaml recipes is readability. For people who don't already spend a lot of time looking at plists, yaml recipes are much easier to parse at a glance. Some examples of yaml recipes are already present in @grahampugh's [recipe repo](https://github.com/autopkg/grahampugh-recipes/tree/master/YAML), and I think the difference is clear:
Aside from the significant reduction in lines needed, there's also no need to escape characters through XML, as demonstrated in the URLTextSearcher regex pattern in the example above.
A secondary benefit of this change is that it includes a lot of the work required …
> Add support for recipes in yaml format

- Code/tests/test_autopkglib.py
- Code/tests/test_preferences.py
AutoPkg's platform detection was changed from `platform.platform()` to `sys.platform` in https://github.com/autopkg/autopkg/commit/8ec51f0cf517eaa472c9147a5cd3fb29225107f5. This PR updates the unit tests to match this change.
Test results:
```
% /usr/local/autopkg/python -m unittest -v tests.test_autopkglib
test_find_binary_posixy (tests.test_autopkglib.TestAutoPkg) ... ok
test_find_binary_windows (tests.test_autopkglib.TestAutoPkg) ... ok
test_get_identifier_from_recipe_file_returns_identifier (tests.test_autopkglib.TestAutoPkg)
get_identifier_from_recipe_file should return identifier. ... ok
test_get_identifier_from_recipe_file_returns_none (tests.test_autopkglib.TestAutoPkg)
get_identifier_from_recipe_file should return None if no identifier. ... WARNING: plist error for fake: …
```
> Update unit tests for platform detection

- Code/autopkg
Previously when passing multiple repos in a single repo-add command, the
log messages don't provide any repo context about the git operations
being applied.
> Show repo path in get_recipe_repo logging

- Code/autopkglib/URLDownloader.py
This change is meant to resolve https://github.com/autopkg/autopkg/issues/713, wherein evaluation of `etag` and `last-modified` headers fail due to comparison of binary strings to text strings.
This `.decode()` was present in AutoPkg 2.2, but was removed in 5ba42491feb9a255c23ed0bf0eb221b9292aa382.
AutoPkg run output follows:
1. First run of Chrome download:
% ./Code/autopkg run -vvcq GoogleChrome.download
Processing GoogleChrome.download...
WARNING: GoogleChrome.download is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLDownloader
{'Input': {'filename': 'GoogleChrome.dmg',
'url': 'https://dl.google.com/chrome/mac/universal/stable/GGRO/googlechrome.dmg'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False …
> Decode binary extended attribute strings in URLDownloader

- Code/autopkg
@macmule pointed out that neither the documentation nor the code says a "data" dictionary is required for summary results, and yet if the dictionary is omitted a KeyError occurs.
This PR updates autopkg to explicitly require a "data" dictionary for processor summary results. If no dictionary is provided, a warning is printed and the summary result is skipped.
Upon merging, the [Processor Summary Reporting](https://github.com/autopkg/autopkg/wiki/Processor-Summary-Reporting) wiki page will also be updated to reflect this requirement.
Using an example processor that doesn't define a "data" dictionary:
```
self.env["example_summary_result"] = {
"summary_text": "This is an example summary result.",
}
```
Here's a snippet of an autopkg run before the change:
```
% ./autopkg/code/autopkg run …
```
> Require "data" dictionary for processor summary results

- Code/autopkglib/AppPkgCreator.py
Adding a feature to allow an alternate version key in `Info.plist`. The `.get` method for the `dict` class allows `NoneType` arguments without throwing a `TypeError` exception. So if `version_key` is unset, it will return `None`, which will in turn return `None` on the `.get` for `infoplist`, defaulting to `CFBundleShortVersionString`.
As I will show in further comments/attachments, this will not affect existing recipes.
> AppPkgCreator: New Optional Input: version_key

- Code/autopkgserver/autopkginstalld
- Code/autopkgserver/autopkgserver
Using `__file__` to get the real path of the executing source doesn't
work when the source is inside a pex archive. This change allows both
`autopkgserver` and `autopkginstalld` to be run from pex archives.
> Use `argv[0]` for permissions checking

- CHANGELOG.md
- Code/autopkg
- Code/autopkglib/version.plist
- Scripts/make_new_release.py
These changes fix some problems already mentioned in Issue #276. Using the common scp syntax for git urls was not properly processed.
We convert those kind of urls to a proper ssh url, so that
`autopkg repo-add git@privategitserver:namespace/repo.git`
is actually equivalent to
`autopkg repo-add ssh://git@privategitserver/namespace/repo.git`
Furthermore we are removing the username – if present – from the url, to keep the directory path free from (probably unwanted) "@" characters.
> Fix handling of scp syntax for git urls

- Code/autopkglib/GitHubReleasesInfoProvider.py
- Code/tests/test_githubreleasesinfoprovider.py
This PR aims to solve https://github.com/autopkg/autopkg/issues/746, in which GitHubReleasesInfoProvider provides an incorrect `version` output for tags that start with `v.` instead of just `v` (as is the case with [Nudge](https://github.com/macadmins/nudge/tags)).
I've also added a couple very rudimentary unit tests for the GitHubReleasesInfoProvider processor, including a test for the fix above.
I'll update this PR soon with test results and verbose output verifying expected behavior.
> Adjust GitHubReleasesInfoProvider to accommodate extra leading dot in version tags

- Code/autopkglib/github/__init__.py
Strip any newlines from the end of the .autopkg_gh_token file. I've also tested it with two newlines.
Reproducde the issue by appending a newline (or two) to ~/.autopkg_gh_token and then run `autopkg info` on the recipe of your choice.
`Code/autopkg info Boot2Docker.munki
Didn't find a recipe for Boot2Docker.munki.
Search GitHub AutoPkg repos for a Boot2Docker.munki recipe? [y/n]: y
Traceback (most recent call last):
File "/Users/jotai/git/autopkg/Code/autopkglib/URLGetter.py", line 177, in execute_curl
errors=errors,
File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/subprocess.py", line 512, in run
output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/curl', '--location', '--silent', '--show-error', '--fail', '--dump-header', '-', …
> Strip newlines from token file

- Code/autopkglib/MunkiImporter.py
This is a redo of https://github.com/autopkg/autopkg/pull/756 that uses the `dev` branch as the base and not `master`
This adds a simple check for `supported_architectures`.
I've checked the following cases
1. Running this on a munki recipe that doesn't have this key. Item was previously imported, but I don't think it matters
```
autopkg run Nudge.munki
Processing Nudge.munki...
Nothing downloaded, packaged or imported.
```
2. Running this for the first time on a recipe designed for Intel
```
autopkg run Docker-x86_64.munki
Processing Docker-x86_64.munki...
The following new items were imported into Munki:
Name    Version  Catalogs  Pkginfo Path                                   Pkg Repo Path                                Icon Repo Path  
----    -------  --------  ------------ …
```
> add check for supported_architectures in MunkiImporter - dev branch

- Code/autopkglib/Unarchiver.py
Resolves https://github.com/autopkg/autopkg/issues/776.
Run output showing the issue described above on the current `dev` branch of AutoPkg:
```
% autopkg run -vv Perforce/HelixALM.pkg.recipe
WARNING: Did not load any default preferences.
Processing Perforce/HelixALM.pkg.recipe...
WARNING: Perforce/HelixALM.pkg.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
PerforceURLProvider
{'Input': {'product': 'HelixALM'}}
PerforceURLProvider: Searching https://cdist2.perforce.com/alm/helixalm/ for r[\d\.]+/
PerforceURLProvider: Searching https://cdist2.perforce.com/alm/helixalm/r2021.2.1/ for ttmacclientinstall\.zip
PerforceURLProvider: Found url: https://cdist2.perforce.com/alm/helixalm/r2021.2.1/ttmacclientinstall.zip
{'Output': {'url': …
```
> Reset archive_format after each Unarchiver process invocation

- Code/autopkglib/URLDownloader.py
Linux requires xattr names to start with "user." This fix allows autopkg on Linux to store extended attributes on downloaded files on some Linux-supported filesystems. ext4, for example, is known to work. Conversely, attempting to store extended attributes on files on NFS mounts is known to still fail.
> Fix for xattr usage on Linux

- Code/autopkglib/GitHubReleasesInfoProvider.py
- Code/tests/test_githubreleasesinfoprovider.py
This PR adds `asset_url` as an additional output variable to the GitHubReleasesInfoProvider processor.
As is, the processor is able to access the releases of a private repository when provided a `GITHUB_TOKEN`, and returns the `browser_download_url` as key `url`. While `curl` and the URLDownloader processor can successfully download an asset of a public repository using the `browser_download_url`, this is not possible for assets in private repositories gated behind authentication. Even if providing `Authorization: token <token>` and `Accept: application/octet-stream` headers to `curl` the download fails with a 404 error for private assets.
Per the [REST API docs](https://docs.github.com/en/rest/reference/releases#get-a-release), you must use the release asset's API-only URL – with the key …
> Add `asset_url` output variable to GitHubReleasesInfoProvider

- Code/autopkglib/MunkiImporter.py
There is a special case when the changes introduced by Erik regarding architecture checking allow MunkiImporter to duplicate a munki import when both arm64 and x86_64 are already imported in the repo.
`_find_matching_pkginfo` return only one item matching a criteria based on hash, app list, receipts... There is a special case when autopkg runs without a Cache and processing a recipe with PkgCreator where `installer_item_hash` will be always different and next criteria can be the same for arm64 and x86_64 recipes. So returning only one item from the catalog could fail when matching this: https://github.com/autopkg/autopkg/blob/1b0031c108f055e1f72e6588776936e4ab797222/Code/autopkglib/MunkiImporter.py#L367-L368
<details>
<summary>Output</summary>
<p>
```shell
joaquin  …
```
> Prevent MunkiImporter duplicating imports when multiple architectures

- Code/autopkglib/MunkiImporter.py
Running `VirtualBoxExtPack.munki` has been failing since the latest autopkg release:
```
autopkg  run VirtualBoxExtPack.munki.recipe 
Processing VirtualBoxExtPack.munki.recipe...
'str' object has no attribute 'get'
Failed.
The following recipes failed:
VirtualBoxExtPack.munki.recipe
Error in local.munki.VirtualBoxExtPack: Processor: MunkiImporter: Error: 'str' object has no attribute 'get'
Nothing downloaded, packaged or imported.
```
This is likely because MunkiImport [tries to find matching packages](https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/MunkiImporter.py#L171) and expects it to either return `None` or [a list](https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/MunkiImporter.py#L380).
Some ([1](https://github.com/autopkg/autopkg/blob/master/Code/autopk …
> Always return list when finding matching pkgs

- Code/autopkg
- Code/autopkglib/autopkgyaml/__init__.py
Attempt to solve https://github.com/autopkg/autopkg/issues/768
This is a quick pass at trying to solve the issue where multiline comment blocks (ie. scalars) in source recipes aren't preserved when autopkg goes to write them to disk via `make-override` or `update-trust-info`.
My approach is to add an autopkg specific representer on the global YAML state that acts on `str` types. It essentially makes every multiline string be a block literal.
Thus far, it has been working for my needs.
Looking for feedback on the approach; I'm open to other ideas!
Ex:
```
Python 3.7.5 (default, May 22 2020, 16:27:59)
[Clang 11.0.0 (clang-1100.0.33.12)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.insert(0, …
```
> Preserve YAML scalar types when writing YAML to disk

- Code/autopkglib/MunkiInstallsItemsCreator.py
This PR adds an option to MunkiInstallsItemsCreator to derive the minimum os version from the installs array.
Currently, MunkiInstallsItemsCreator can generate installs arrays like the below:
```
MunkiInstallsItemsCreator: Created installs item for /Applications/Listento.app
{'Output': {'additional_pkginfo': {'installs': [{'CFBundleIdentifier': 'com.audiomovers.standalone',
'CFBundleName': 'Listento',
'CFBundleShortVersionString': '1.10.20210419',
'CFBundleVersion': '1.10.20210419',
'minosversion': '10.11',
'path': '/Applications/Listento.app',
'type': 'application',
'version_comparison_key': 'CFBundleShortVersionString'}]}}}
```
In this example, there is a value for `minosversion`, but this doesn't make it into the title properly as needs to be passed to the `minimum_os_version` key …
> MunkiInstallsItemsCreator.py - Add option to derive minimum os version

- .github/workflows/tests.yaml
the cron schedule was incorrect, causing this to run too often.
> Update tests.yaml - remove bad schedule

- Code/autopkglib/URLGetter.py
Fix URLGetter for cases where default windows curl is used.
> Fix URLGetter.py when default windows curl is used.

- Code/autopkglib/GitHubReleasesInfoProvider.py
add the ability to get the asset created_at time. See example JSON here: https://api.github.com/repos/autopkg/autopkg/releases/latest
The GitHub action to test this processor specifically is in this PR: https://github.com/autopkg/autopkg/pull/783
> Update GitHubReleasesInfoProvider.py to get asset_created_at time

- Code/autopkglib/xattr.py
xattr does not work in some Linux file systems, or in Linux running under WSL, or in some docker containers in general. This will make the failures of xattr no longer hard errors in these cases.
Use of xattr for storing etag data is not ideal in the first place and is already solved in URLDownloaderPython by using a json metadata file instead, but this will help with compatibility in general for older methods. This will have the drawback of not detecting that the already downloaded file is the same correctly due to lack of metadata for any recipe currently relying on xattr. That said, redownloading the file seems better than throwing hard errors.
I believe the behavior should be similar to how these older methods work on Windows today since on Windows xattr is no-op within autopkg.
> Update xattr.py to not throw hard errors on some Linux systems.

- Code/autopkglib/PkgPayloadUnpacker.py
Modern Apple Archives fail to be extracted using `ditto`. Case in point is TeamViewer.pkg in justinrimmel-recipes.
In Slack's `#autopkg` channel we have established that the `aa` command can do the job instead. In fact, it seems to also be able to extract the Payload archives that are not modern Apple Archives but CPIO archive payloads.
However, `aa` only appears to have been introduced on Big Sur, so can't replace `ditto` just yet.
This PR makes PkgPayloadUnpacker try `aa` only if `ditto` fails and `aa` is found at `/usr/bin/aa`. If `aa` is not present, the `ditto` failure is raised as a ProcessorError.
> When "ditto" fails to extract an archive in PkgPayloadUnpacker, use "aa" if present

- .github/workflows/TestGitHubReleasesInfoProvider.yaml
- Code/autopkglib/github/__init__.py
This should resolve https://github.com/autopkg/autopkg/pull/764 (see discussion there)
This will allow GitHubInfoReleasesProvider to work on Windows for releases which contain unusual characters. It will require Python3.6+ on Windows, but will not induce that requirement for non-Windows. Reference: https://docs.python.org/3/library/json.html#json.load
I think this is a better approach since the encoding could be any of "UTF-8, UTF-16 or UTF-32" and this approach should work, rather than specifically forcing "UTF-8" to be the one used for decoding. From the footnote: "Changed in version 3.6: fp can now be a binary file. The input encoding should be UTF-8, UTF-16 or UTF-32."
This approach also has the advantage of not affecting the current typical behavior at all.
> Fix GitHubInfoReleasesProvider on Windows in case of non-ascii characters

- gh_actions_requirements.txt
Remove pin of certifi, see here: https://github.com/autopkg/autopkg/issues/832
> remove version pin of certifi to allow newer Root CAs

- .pre-commit-config.yaml
The flake8 repo has relocated: https://github.com/PyCQA/flake8/issues/1737
> Update pre-commit config, including new flake8 repo URL

- Code/autopkgserver/autopkginstalld
- Code/autopkgserver/installer.py
Fixes autopkginstalld (and thus running .install recipes) under macOS 11.0 and later. Code was checking the second "position" of the os version to see if it was running on macOS 10.10 or later. Autopkg is no longer supported under 10.9 or earlier, so easiest to just remove the conditional imports.
> Autopkginstalld fix

- Code/autopkgserver/autopkginstalld
- Code/autopkgserver/installer.py
This brings dev up to date with master.
* Fix conditional imports of launchd code that broke under macOS 11.0 (and later)
* Fix for minor installer output 'quirk' (at least under macOS 13)
> Autopkginstalld fix (#838)

- Code/autopkglib/SparkleUpdateInfoProvider.py
PR #834 introduced a bug in which only the _last_ item in a Sparkle feed was evaluated. This PR offers another method to accomplish the same goals for #834, while hopefully avoiding any regressions.
Just prior to #834's merge, SparkleUpdateInfoProvider correctly evaluated the "latest" version available in a multi-item Sparkle feed, as demonstrated below (2.2.0 is the latest version):
```
% git checkout 2007b522bded3d35509affc088f0e4b7f505ec35
HEAD is now at 2007b52 Autopkginstalld fix (#838)
% ./Code/autopkg run -vvcq "~/Library/AutoPkg/Recipes/Elliot Jordan/Recipe Robot.download.recipe"
Processing ~/Library/AutoPkg/Recipes/Elliot Jordan/Recipe Robot.download.recipe...
WARNING: ~/Library/AutoPkg/Recipes/Elliot Jordan/Recipe Robot.download.recipe is missing trust info and …
```
> Redesign SparkleUpdateInfoProvider channel support

- Code/autopkg
As mentioned in https://github.com/autopkg/autopkg/issues/859, PyYAML does not indent `-` (and other block collection indicators) according to the YAML indentation [spec](https://yaml.org/spec/1.2-old/spec.html#id2777534).
This is a cosmetic difference, and [some disagree](https://stackoverflow.com/a/39681672) that the indentation is counter to the spec, but the fix is simple enough and may improve compatibility with certain YAML parsers.
Test output forthcoming.
> Indent block collection characters to comply with spec

- Code/autopkglib/URLGetter.py
This addresses issue #822 by adding back in the two lines of code from https://github.com/autopkg/autopkg/commit/ce72f18af711b8c3269fc399424f7859bc8e1b0b that we removed in a later commit.
I've been running this patch locally for several months without issue.  I've attached a before and after verbose run on a recipe that triggers the problem.
[output-before.txt](https://github.com/autopkg/autopkg/files/10239748/output-before.txt)
[output-after.txt](https://github.com/autopkg/autopkg/files/10239750/output-after.txt)
> Add back error handing to address issue 822

- CHANGELOG.md
- Code/autopkglib/PkgCopier.py
- Code/autopkglib/SparkleUpdateInfoProvider.py
- Code/autopkglib/version.plist
Currently, PkgCopier copies the item supplied regardless of whether it is a package or not. This PR adds a simple check on the filename of the source_pkg to see if it ends in 'pkg' (which would allow .pkg and .mpkg). It is not meant to be exhaustive, just something to highlight a recipe error.
1. Current processor when user supplies a dmg instead of a pkg as the source_pkg
```
autopkg run FCPContent.pkg -p /Users/apuser/Library/AutoPkg/Cache/com.github.jazzace.pkg.FCPContent/downloads/FCPContent.dmg -vvvv
Processing FCPContent.pkg...
{'AUTOPKG_VERSION': '2.7.2',
'FAIL_RECIPES_WITHOUT_TRUST_INFO': True,
'GIT_PATH': '/usr/local/git/bin/git',
'NAME': 'FCPContent',
'PARENT_RECIPES': ['/Users/apuser/Library/AutoPkg/RecipeRepos/com.github.autopkg.jazzace-recipes/AppleProVideo/FinalCutProXContent …
```
> Add pkg check to PkgCopier

- Code/autopkglib/URLGetter.py
So, this may be an _extremely_ rare issue...but came across it on the recipe `com.github.moofit-recipes.download.MirrorOp` and I described it in https://github.com/autopkg/moofit-recipes/pull/126.
To re-cap here:
The web server is not accepting, or allowing, the etag `If-None-Match` and last modified `If-Modified-Since` header checks.  If these are included, then the web server will return a 400, but if they are not, it processes the request as expected.  Not quite sure why they're not supporting this as it literally should be saving them bandwidth...
When setting `CHECK_FILESIZE_ONLY` as `True` in the `URLDownloader` processor step, the parent class `URLGetter` processor still adds the etag and last modified headers to the call.
I'm not sure if this was an oversight or by design, but as …
> Don't add etag/last_modified headers if CHECK_FILESIZE_ONLY == True

- .github/workflows/tests.yaml
fix autopkg tests by having it generate recipe map.
> fix github action unittests tests.yaml

- Code/autopkg
The word "processor" in the description for find_processor_info (autopkg core code) is short one "s".
If you want tests to show that fixing this typo does not affect the code, please advise.
> Fix typo in find_processor_info description

- Code/autopkglib/URLDownloader.py
This reverts https://github.com/autopkg/autopkg/pull/626 which was added due to https://github.com/autopkg/autopkg/issues/624. 
Previously, combining `--head` and `--request GET` allowed curl to perform a GET request and stop after receiving the headers. This workaround was added to handle servers that return HTTP Forbidden or incorrect headers for a HEAD request. However, with the update to curl 8.6.0 on macOS 14.5, this combination results in an error ("curl: (8) Weird server reply").
> Fix curl command error in URLDownloader.prefetch_filename()

- Code/autopkglib/URLDownloaderPython.py
This change fixes the descriptions on a couple input variables in the `URLDownloaderPython` processor. The old descriptions were the result of a bad copy and paste of the `PKG` input variable.
> Fix `URLDownloaderPython` input_variables descriptions

- Code/autopkglib/FindAndReplace.py
Add ability to set custom output variable name.
I was already doing basically the same thing in some of my other processors, so I basically lift and shifted the code to this one.
Example output from a [test recipe](https://github.com/jgstew/jgstew-recipes/blob/main/Recipes-Examples/FindAndReplace.test.recipe.yaml):
```
Processing com.github.jgstew.test.FindAndReplace...
WARNING: com.github.jgstew.test.FindAndReplace is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
FindAndReplace
{'Input': {'find': '_',
'input_string': '1_2_3',
'replace': '.',
'replace_output_var': 'version'}}
FindAndReplace: Replacing "_" with "." in "1_2_3".
{'Output': {'version': '1.2.3'}}
com.github.jgstew.SharedProcessors/AssertInputContainsString
{'Input': {'assert_string': '1.2.3', …
```
> Allow custom output variable name for FindAndReplace Processor

- Code/autopkglib/FindAndReplace.py
tweak FindAndReplace.py
Discussion on this in Slack DMs with @homebysix  
This allows the value of the output variable to show up in the verbose output, in a similar but simpler way to how URLTextSearcher does it. (URLTextSearcher allows multiple named group outputs in addition to the default one, FindAndReplace only allows 1 output.)
> tweak FindAndReplace.py to show output value in verbose output.

- Code/autopkglib/__init__.py
This PR contains 3 changes to `autopkglib/__init__.py` which were found to be needed in order to run a customer processor with command line usage/arguments (as per: [https://github.com/autopkg/autopkg/wiki/Developing-Custom-Processors#sample-usage---command-line-argumentsvariables](https://github.com/autopkg/autopkg/wiki/Developing-Custom-Processors#sample-usage---command-line-argumentsvariables)).
I also raised a discussion on this: [https://github.com/autopkg/autopkg/discussions/952](https://github.com/autopkg/autopkg/discussions/952)
Basically, running a custom processors with a plist works.. but found that running custom processors via command line usage/arguments did not.. and found another issue too.
I'm happy though to have this PR closed without merging, if it's decided to just …
> Changes to allow running custom processors via command line usage/arguments

- Code/autopkglib/URLDownloaderPython.py
This PR adds a small change into `ssl_context_certifi(self)` that will use the certificate bundle defined in the `SSL_CERT_FILE` environment variable if set.
It's common for SSL Inspection to be used on corp networks and this allows users to use this processor without needing to disable SSL validation with the `disable_ssl_validation` input.
> Updating to pull cert bundle from SSL_CERT_FILE if set
